name: Build and Deploy a Test Website
on: pull_request

jobs:
  build-and-deploy-test:
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build
        run: |
          PR_NO=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          SUBDIR="PR_${PR_NO}"
          echo "::debug::Building site for Pull Request #${PR_NO}"
          npm i
          npx gulp
          mv html $SUBDIR
          echo "::debug::Cloning current site"
          git clone https://github.com/qooxdoo/website.git --depth=1 --branch=gh-pages  ./html
          rm -rf ./html/.git
          echo "::debug::Publishing site in subdirectory $SUBDIR"
          mv $SUBDIR ./html/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
