name: Build a Pull Request version of the website and deploy to subdir
on: pull_request

jobs:
  build-and-deploy-pr:
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build
        run: |
          PR_NO=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          SUBDIR="PR_${PR_NO}"
          npm i
          npx gulp
          mv html $SUBDIR
          git clone https://github.com/qooxdoo/website.git --depth=1 --branch=gh-pages  ./html
          rm -rf ./html/.git
          rm -rf ./html/$SUBDIR || true
          mv $SUBDIR ./html/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html

      - name: Post message to Pull Request
        uses: unsplash/comment-on-pr@master
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "The website in the version of this PR has been published at http://qooxdoo.org/website/PR_${pull request number}"
          check_for_duplicate_msg: false  # OPTIONAL
